version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - saas-net
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/flowbit_saas
      - JWT_SECRET=supersecretkey
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - saas-net

  shell:
    build: ./shell
    container_name: shell
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://api:8000
    depends_on:
      - api
      - support-tickets-app
    networks:
      - saas-net

  support-tickets-app:
    build: ./micro-apps/support-tickets-app
    container_name: support-tickets-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - saas-net
  
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_URL=http://localhost:5678
    networks:
      - saas-net

volumes:
  mongo-data:

networks:
  saas-net:
